@startuml oop_lecture

skinparam class {
BackgroundColor White
ArrowColor FireBrick
BorderColor Black
}

skinparam classAttributeIconSize 0

' class MyClass {
'     +attribute1: Type
'     -attribute2: Type
'     #attribute3: Type
'     +method1(parameter1: Type, parameter2: Type): Return Type
'     -method2(parameter1: Type, parameter2: Type): Return Type
'     +method3(parameter1: Type, parameter2: Type): Return Type
' }


package university <<Frame>> {

struct Date{
    +day_: Integer
    +month_: Integer
    +year_: Integer
}

abstract class Person {
    #name_: String
    #date_of_birth_: Date
    #email_: String
    #phone_number_: String
    #department_: Department
    +log_in(): void
+log_out(): void
+change_password(): void
}

class Student {
    -student_id_: String
    -courses_: Collection<Course>
    -grades_: Collection<Float>
    +enroll(course_id: String): void
    +drop_course(course_id: String): void
    +view_grades(): void
    +submit_assignment(assignment_id: String, course_id: String): void
    +take_quiz(quiz_id: String, course_id: String): void
}

class Professor {
    -professor_id_: String
    -title_: String
    -courses_: Collection<Course>
    +teach_course(course_id: String)
    +assign_grade(student_id: String, course_id: String, grade: String): void
}

class Administrator {
    -administrator_id_: String
    -role_: String
    +manage_course(course_id: String, action: String): void
    +manage_student(student_id: String, course_id: String, action: String): void
    +manage_professor(professor_id: String, course_id: String, action: String): void
}

class Course {
    -course_id_: String
    -name_: String
    -credits_: int
    -professors_: Collection<Professor>
    -students_: Collection<Student>
    +get_course_details(): void
    +list_students(): void
    +list_professors(): void
}

class Department {
    -department_id_: String
    -name_: String
    -professors_: Collection<Professor>
    -students_: Collection<Student>
    -courses_: Collection<Course>
    +add_course(course_id: String): void
    +enroll_student(student_id: String, course_id: String): void
    +assign_professor(professor_id: String, course_id: String): void
}

Person <|-- Student
Person <|-- Professor
Person <|-- Administrator

Date -- Person: uses <

Department "1..*" *-- "1" Course

Department "1..*" o-- "1..*" Person

Professor "1..*" -- "1..*" Course : teaches >
Student "1..*" -- "1..*" Course : enrolls in >
Professor "1..*" -- "1..*" Student : advises >

' Student -- Course : enrolls in >
' Professor -- Course : teaches >
' Professor -- Student : advises >
Department "1..*" -- "1" Administrator : supervises >
}

@enduml